version: '3'
services:
  frontend:
    build: ./ReactWEB
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./ExpressREST
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production